import { Router } from "express";
import type { TransferMovement } from "../../shared/types";

/** Mock data de la route. MarketView l'appelle avec un vrai fetch("/api/transfers"). */
const MOCK_TRANSFER: TransferMovement[] = [
  {
    id: "lacazette-lyon-marseille-2026-08-22",
    playerName: "Alexandre Lacazette",
    avatarUrl: "https://media.api-sports.io/football/players/1467.png",
    fromTeam: "Lyon",
    toTeam: "Olympique de Marseille",
    description: "Marseille sonde Lyon pour un renfort offensif d'expérience en fin de mercato.",
    amount: "—",
    time: "22 août 2026",
    date: "2026-08-22",
    type: "Rumor",
    confidence: 62,
    statusLabel: "Dossier très chaud",
  },
  {
    id: "david-juventus-lille-2026-08-14",
    playerName: "Jonathan David",
    avatarUrl: "https://media.api-sports.io/football/players/8489.png",
    fromTeam: "Juventus FC",
    toTeam: "Lille",
    fromTeamLogo: "https://media.api-sports.io/football/teams/496.png",
    toTeamLogo: "https://media.api-sports.io/football/teams/79.png",
    description: "Retour à Lille du buteur canadien, sous contrat jusqu'en juin 2030.",
    amount: "32 M€",
    time: "14 août 2026",
    date: "2026-08-14",
    type: "Official",
  },
  {
    id: "dembele-psg-psg-2026-07-02",
    playerName: "Ousmane Dembélé",
    avatarUrl: "https://media.api-sports.io/football/players/153.png",
    fromTeam: "Paris Saint Germain",
    toTeam: "Paris Saint Germain",
    fromTeamLogo: "https://media.api-sports.io/football/teams/85.png",
    toTeamLogo: "https://media.api-sports.io/football/teams/85.png",
    description: "Contrat prolongé jusqu'en juin 2029 après une saison à 14 buts.",
    amount: "Prolongation",
    time: "2 juillet 2026",
    date: "2026-07-02",
    type: "Prolongation",
  },
  {
    id: "neves-benfica-psg-2026-08-10",
    playerName: "João Neves",
    avatarUrl: "https://img.a.transfermarkt.technology/portrait/big/670681-1701295511.jpg?lm=4711",
    fromTeam: "Benfica",
    toTeam: "Paris Saint Germain",
    toTeamLogo: "https://media.api-sports.io/football/teams/85.png",
    description: "Le milieu portugais prolonge officiellement son bail parisien jusqu'en 2031.",
    amount: "60 M€",
    time: "14 août 2026",
    date: "2026-08-14",
    type: "Official",
  },
  {
    id: "bouaddi-lille-real-madrid-2026-08-20",
    playerName: "Ayyoub Bouaddi",
    avatarUrl: "https://img.a.transfermarkt.technology/portrait/header/1097139-1741119960.jpg?lm=4711",
    fromTeam: "Lille",
    toTeam: "Real Madrid",
    fromTeamLogo: "https://media.api-sports.io/football/teams/79.png",
    description: "Le Real surveille le jeune milieu lillois en vue du prochain mercato.",
    amount: "—",
    time: "20 août 2026",
    date: "2026-08-20",
    type: "Rumor",
    confidence: 34,
    statusLabel: "Piste éteinte",
  },
  {
    id: "tessmann-lyon-atalanta-2026-08-19",
    playerName: "Tanner Tessmann",
    avatarUrl: "https://img.a.transfermarkt.technology/portrait/big/670096-1722196121.jpg?lm=4711",
    fromTeam: "Lyon",
    toTeam: "Atalanta",
    fromTeamLogo: "https://media.api-sports.io/football/teams/80.png",
    description: "L'Atalanta formalise une offre pour le milieu défensif américain.",
    amount: "18 M€",
    time: "19 août 2026",
    date: "2026-08-19",
    type: "Rumor",
    confidence: 71,
    statusLabel: "Dossier très chaud",
  },
  {
    id: "baidoo-lens-dortmund-2026-08-05",
    playerName: "Samson Baidoo",
    avatarUrl: "https://img.a.transfermarkt.technology/portrait/big/655217-1722523870.png?lm=4711",
    fromTeam: "RC Lens",
    toTeam: "Borussia Dortmund",
    fromTeamLogo: "https://media.api-sports.io/football/teams/116.png",
    description: "Dortmund entame des discussions préliminaires pour le défenseur autrichien.",
    amount: "—",
    time: "5 août 2026",
    date: "2026-08-05",
    type: "Rumor",
    confidence: 48,
    statusLabel: "Négociations",
  },
  {
    id: "bacher-lyon-lyon-2026-07-28",
    playerName: "Félix Bacher",
    avatarUrl: "https://img.a.transfermarkt.technology/portrait/big/394134-1724845183.jpg?lm=4711",
    fromTeam: "Lyon",
    toTeam: "Lyon",
    fromTeamLogo: "https://media.api-sports.io/football/teams/80.png",
    toTeamLogo: "https://media.api-sports.io/football/teams/80.png",
    description: "Contrat prolongé jusqu'en juin 2028 pour le défenseur central.",
    amount: "Prolongation",
    time: "28 juillet 2026",
    date: "2026-07-28",
    type: "Prolongation",
  },
  {
    id: "sidibe-lemans-monaco-2026-08-24",
    playerName: "Djibril Sidibé",
    avatarUrl: "https://img.a.transfermarkt.technology/portrait/big/161869-1604261378.jpg?lm=4711",
    fromTeam: "Le Mans FC",
    toTeam: "AS Monaco",
    description: "Monaco cherche un latéral d'expérience pour la fin du mercato.",
    amount: "—",
    time: "24 août 2026",
    date: "2026-08-24",
    type: "Rumor",
    confidence: 40,
    statusLabel: "Refusé",
  },
];

const router = Router();

/**
 * Marché des transferts. Le filtrage par période vit côté front (MarketView).
 * Revalidation à chaque appel : 304 tant que l'ETag n'a pas changé.
 */
router.get("/", (_req, res) => {
  res.set("Cache-Control", "no-cache");
  res.json({ transfers: MOCK_TRANSFER });
});

export default router;
