import { Player } from "./types";

// Dynamic search suggestion definition
export interface SuggestionPlayer {
  id: string;
  name: string;
  fullName: string;
  team: string;
  positionLong: string;
  position: string;
  form: number;
  avatarUrl: string;
}

export const POPULAR_PLAYERS: SuggestionPlayer[] = [
  {
    id: "yamal",
    name: "Yamal",
    fullName: "Lamine Yamal",
    team: "FC Barcelone",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 94,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Lamine_Yamal_2024.jpg/250px-Lamine_Yamal_2024.jpg",
  },
  {
    id: "kane",
    name: "Kane",
    fullName: "Harry Kane",
    team: "Bayern Munich",
    positionLong: "Attaquant de pointe",
    position: "A",
    form: 91,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Harry_Kane_2024.jpg/250px-Harry_Kane_2024.jpg",
  },
  {
    id: "messi",
    name: "Messi",
    fullName: "Lionel Messi",
    team: "Inter Miami",
    positionLong: "Attaquant Créateur",
    position: "A",
    form: 88,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lionel_Messi_20180626.jpg/250px-Lionel_Messi_20180626.jpg",
  },
  {
    id: "ronaldo",
    name: "Ronaldo",
    fullName: "Cristiano Ronaldo",
    team: "Al-Nassr",
    positionLong: "Buteur",
    position: "A",
    form: 87,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis_FC_at_Azadi_Stadium_19_September_2023.jpg/250px-Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis_FC_at_Azadi_Stadium_19_September_2023.jpg",
  },
  {
    id: "lewandowski",
    name: "Lewandowski",
    fullName: "Robert Lewandowski",
    team: "FC Barcelone",
    positionLong: "Attaquant de pointe",
    position: "A",
    form: 89,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Robert_Lewandowski_2024.jpg/250px-Robert_Lewandowski_2024.jpg",
  },
  {
    id: "pedri",
    name: "Pedri",
    fullName: "Pedri González",
    team: "FC Barcelone",
    positionLong: "Milieu Organisateur",
    position: "M",
    form: 86,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Pedri_2024.jpg/250px-Pedri_2024.jpg",
  },
  {
    id: "musiala",
    name: "Musiala",
    fullName: "Jamal Musiala",
    team: "Bayern Munich",
    positionLong: "Milieu Offensif",
    position: "M",
    form: 92,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Jamal_Musiala_2024.jpg/250px-Jamal_Musiala_2024.jpg",
  },
  {
    id: "wirtz",
    name: "Wirtz",
    fullName: "Florian Wirtz",
    team: "Bayer Leverkusen",
    positionLong: "Milieu Créatif",
    position: "M",
    form: 93,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Florian_Wirtz_2024.jpg/250px-Florian_Wirtz_2024.jpg",
  },
  {
    id: "son",
    name: "Son",
    fullName: "Heung-min Son",
    team: "Tottenham Hotspur",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 85,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Son_Heung-min_2022.jpg/250px-Son_Heung-min_2022.jpg",
  },
  {
    id: "odegaard",
    name: "Ødegaard",
    fullName: "Martin Ødegaard",
    team: "Arsenal",
    positionLong: "Milieu Créatif",
    position: "M",
    form: 90,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Martin_%C3%98degaard_2022.jpg/250px-Martin_%C3%98degaard_2022.jpg",
  },
  {
    id: "palmer",
    name: "Palmer",
    fullName: "Cole Palmer",
    team: "Chelsea",
    positionLong: "Milieu Offensif / Ailier",
    position: "M",
    form: 92,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Cole_Palmer_2023_%28cropped%29.jpg/250px-Cole_Palmer_2023_%28cropped%29.jpg",
  },
  {
    id: "foden",
    name: "Foden",
    fullName: "Phil Foden",
    team: "Manchester City",
    positionLong: "Milieu Offensif",
    position: "M",
    form: 88,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Phil_Foden_2023.jpg/250px-Phil_Foden_2023.jpg",
  },
  {
    id: "rodri",
    name: "Rodri",
    fullName: "Rodrigo Hernández",
    team: "Manchester City",
    positionLong: "Milieu Défensif",
    position: "M",
    form: 95,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Rodrigo_Hern%C3%A5ndez_Cascante_2024.jpg/250px-Rodrigo_Hern%C3%A5ndez_Cascante_2024.jpg",
  },
  {
    id: "rice",
    name: "Rice",
    fullName: "Declan Rice",
    team: "Arsenal",
    positionLong: "Milieu Récupérateur",
    position: "M",
    form: 89,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Declan_Rice_2024.jpg/250px-Declan_Rice_2024.jpg",
  },
  {
    id: "vandijk",
    name: "van Dijk",
    fullName: "Virgil van Dijk",
    team: "Liverpool",
    positionLong: "Défenseur Central",
    position: "D",
    form: 91,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Virgil_van_Dijk_2024.jpg/250px-Virgil_van_Dijk_2024.jpg",
  },
  {
    id: "saliba",
    name: "Saliba",
    fullName: "William Saliba",
    team: "Arsenal",
    positionLong: "Défenseur Central",
    position: "D",
    form: 90,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/William_Saliba_2024.jpg/250px-William_Saliba_2024.jpg",
  },
  {
    id: "rudiger",
    name: "Rüdiger",
    fullName: "Antonio Rüdiger",
    team: "Real Madrid",
    positionLong: "Défenseur Central",
    position: "D",
    form: 88,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Antonio_R%C3%BCdiger_2024.jpg/250px-Antonio_R%C3%BCdiger_2024.jpg",
  },
  {
    id: "dembele",
    name: "Dembélé",
    fullName: "Ousmane Dembélé",
    team: "PSG",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 84,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Ousmane_Demb%C3%A9l%C3%A9_2020.jpg/250px-Ousmane_Demb%C3%A9l%C3%A9_2020.jpg",
  },
  {
    id: "barcola",
    name: "Barcola",
    fullName: "Bradley Barcola",
    team: "PSG",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 87,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Bradley_Barcola_2024.jpg/250px-Bradley_Barcola_2024.jpg",
  },
  {
    id: "zaireemery",
    name: "Zaïre-Emery",
    fullName: "Warren Zaïre-Emery",
    team: "PSG",
    positionLong: "Milieu Central",
    position: "M",
    form: 85,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Warren_Za%C3%AFre-Emery_2024.jpg/250px-Warren_Za%C3%AFre-Emery_2024.jpg",
  },
  {
    id: "maignan",
    name: "Maignan",
    fullName: "Mike Maignan",
    team: "AC Milan",
    positionLong: "Gardien de But",
    position: "G",
    form: 86,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Mike_Maignan_2024.jpg/250px-Mike_Maignan_2024.jpg",
  },
  {
    id: "courtois-player",
    name: "Courtois",
    fullName: "Thibaut Courtois",
    team: "Real Madrid",
    positionLong: "Gardien de But",
    position: "G",
    form: 89,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Thibaut_Courtois_2018.jpg/250px-Thibaut_Courtois_2018.jpg",
  },
  {
    id: "martinez-lautaro",
    name: "Martínez",
    fullName: "Lautaro Martínez",
    team: "Inter Milan",
    positionLong: "Buteur",
    position: "A",
    form: 88,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Lautaro_Mart%C3%ADnez_2024.jpg/250px-Lautaro_Mart%C3%ADnez_2024.jpg",
  },
  {
    id: "leao",
    name: "Leão",
    fullName: "Rafael Leão",
    team: "AC Milan",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 86,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Rafael_Le%C3%A3o_2024.jpg/250px-Rafael_Le%C3%A3o_2024.jpg",
  },
  {
    id: "kvaratskhelia",
    name: "Kvaratskhelia",
    fullName: "Khvicha Kvaratskhelia",
    team: "Napoli",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 85,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Khvicha_Kvaratskhelia_2024.jpg/250px-Khvicha_Kvaratskhelia_2024.jpg",
  },
  {
    id: "osimhen",
    name: "Osimhen",
    fullName: "Victor Osimhen",
    team: "Galatasaray",
    positionLong: "Attaquant de pointe",
    position: "A",
    form: 87,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Victor_Osimhen_2024.jpg/250px-Victor_Osimhen_2024.jpg",
  },
  {
    id: "valverde",
    name: "Valverde",
    fullName: "Federico Valverde",
    team: "Real Madrid",
    positionLong: "Milieu Polyvalent",
    position: "M",
    form: 90,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Federico_Valverde_2024.jpg/250px-Federico_Valverde_2024.jpg",
  },
  {
    id: "gavi",
    name: "Gavi",
    fullName: "Pablo Gavi",
    team: "FC Barcelone",
    positionLong: "Milieu Combactif",
    position: "M",
    form: 82,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Gavi_2024.jpg/250px-Gavi_2024.jpg",
  },
  {
    id: "hakimi",
    name: "Hakimi",
    fullName: "Achraf Hakimi",
    team: "PSG",
    positionLong: "Défenseur Latéral Droit",
    position: "D",
    form: 88,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Achraf_Hakimi_2024.jpg/250px-Achraf_Hakimi_2024.jpg",
  },
  {
    id: "davies",
    name: "Davies",
    fullName: "Alphonso Davies",
    team: "Bayern Munich",
    positionLong: "Défenseur Latéral Gauche",
    position: "D",
    form: 86,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Alphonso_Davies_2024.jpg/250px-Alphonso_Davies_2024.jpg",
  },
  {
    id: "hernandez",
    name: "Hernández",
    fullName: "Theo Hernández",
    team: "AC Milan",
    positionLong: "Défenseur Latéral Gauche",
    position: "D",
    form: 87,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Theo_Hern%C3%A5ndez_2024.jpg/250px-Theo_Hern%C3%A5ndez_2024.jpg",
  },
  {
    id: "donnarumma",
    name: "Donnarumma",
    fullName: "Gianluigi Donnarumma",
    team: "PSG",
    positionLong: "Gardien de But",
    position: "G",
    form: 85,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Gianluigi_Donnarumma_2024.jpg/250px-Gianluigi_Donnarumma_2024.jpg",
  },
  {
    id: "terstegen",
    name: "ter Stegen",
    fullName: "Marc-André ter Stegen",
    team: "FC Barcelone",
    positionLong: "Gardien de But",
    position: "G",
    form: 83,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Marc-Andr%C3%A9_ter_Stegen_2024.jpg/250px-Marc-Andr%C3%A9_ter_Stegen_2024.jpg",
  },
  {
    id: "silva-bernardo",
    name: "Silva",
    fullName: "Bernardo Silva",
    team: "Manchester City",
    positionLong: "Milieu Organisateur",
    position: "M",
    form: 87,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Bernardo_Silva_2024.jpg/250px-Bernardo_Silva_2024.jpg",
  },
  {
    id: "fernandes",
    name: "Fernandes",
    fullName: "Bruno Fernandes",
    team: "Manchester United",
    positionLong: "Milieu Offensif",
    position: "M",
    form: 86,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Bruno_Fernandes_2024.jpg/250px-Bruno_Fernandes_2024.jpg",
  },
  {
    id: "rashford",
    name: "Rashford",
    fullName: "Marcus Rashford",
    team: "Manchester United",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 81,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Marcus_Rashford_2024.jpg/250px-Marcus_Rashford_2024.jpg",
  },
  {
    id: "diaz",
    name: "Díaz",
    fullName: "Luis Díaz",
    team: "Liverpool",
    positionLong: "Attaquant Ailier",
    position: "A",
    form: 88,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Luis_D%C3%ADaz_2024.jpg/250px-Luis_D%C3%ADaz_2024.jpg",
  },
  {
    id: "macallister",
    name: "Mac Allister",
    fullName: "Alexis Mac Allister",
    team: "Liverpool",
    positionLong: "Milieu Organisateur",
    position: "M",
    form: 87,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Alexis_Mac_Allister_2024.jpg/250px-Alexis_Mac_Allister_2024.jpg",
  },
  {
    id: "arnold",
    name: "Alexander-Arnold",
    fullName: "Trent Alexander-Arnold",
    team: "Liverpool",
    positionLong: "Défenseur Latéral Droit",
    position: "D",
    form: 89,
    avatarUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Trent_Alexander-Arnold_2024.jpg/250px-Trent_Alexander-Arnold_2024.jpg",
  }
];
